name: Main Branch CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
          server-id: 'github'

      - name: Build with Maven
        run: |
          mvn clean package

      - name: Run Tests
        run: |
          mvn test

      - name: Increment Version (for Snapshots)
        if: github.ref == 'refs/heads/main'
        run: |
          NEW_VERSION=1.0.${{ github.run_number }}
          mvn versions:set -DnewVersion=$NEW_VERSION-SNAPSHOT
          mvn clean package
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update snapshot version to $NEW_VERSION-SNAPSHOT"
          git push 

      - name: Deploy to GitHub Packages (Optional)
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn deploy
